settings:
  title: 'ClickNow Status Pages'
  url: 'https://status.clicknow.my.id' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram, default=90
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: clicknow-fansub # unique identifier
    name: ClickNow Site
    description: 'ClickNow Fansub Site' # default=empty
    url: 'https://clicknow.my.id/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: simpenan-clicknow
    name: Simpenan ClickNow
    description: 'Files for ClickNow '
    url: 'https://simpenan.clicknow.my.id/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: zentonator-clicknow-site
    name: Zentonator Portofolio Site
    url: 'https://zentonator.clicknow.my.id/'
    method: GET
    expectStatus: 200

  - id: yorsha # unique identifier
    name: Yorsha Site
    description: 'Yorsha Site' # default=empty
    url: 'https://yorsha.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: yorsha-topup # unique identifier
    name: Topup Yorsha
    description: 'Topup Yorsha Site' # default=empty
    url: 'https://topup.yorsha.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
